"""empty message

Revision ID: 1ed9919350d8
Revises: bb9094880b59
Create Date: 2020-05-21 20:17:49.794498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed9919350d8'
down_revision = 'bb9094880b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plUser', 'login_email',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('plUser', 'password_hash',
                    existing_type=sa.VARCHAR(length=128),
                    nullable=False)
    op.alter_column('plUser', 'username',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plUser', 'username',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=True)
    op.alter_column('plUser', 'password_hash',
                    existing_type=sa.VARCHAR(length=128),
                    nullable=True)
    op.alter_column('plUser', 'login_email',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    # ### end Alembic commands ###
