"""Profile Table

Revision ID: 4243898e7978
Revises: bb9094880b59
Create Date: 2020-05-26 14:36:31.149351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4243898e7978'
down_revision = 'bb9094880b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profile',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('profile_pics', sa.ARRAY(
            sa.String(length=64)), nullable=True),
        sa.Column('location', sa.String(length=64), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('expertise', sa.ARRAY(
            sa.String(length=64)), nullable=True),
        sa.Column('linkedin_profile', sa.String(
            length=64), nullable=True),
        sa.Column('angelco_profile', sa.String(
            length=64), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['plUser.id'], ),
        sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
