"""Create table Project, with initial states

Revision ID: 61ff6848a9c2
Revises: bb9094880b59
Create Date: 2020-05-21 22:26:59.007709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ff6848a9c2'
down_revision = 'bb9094880b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=64), nullable=False),
        sa.Column('plUser_id', sa.Integer(), nullable=False),
        sa.Column('subtitle', sa.Text(), nullable=True),
        sa.Column('industry', sa.Text(), nullable=True),
        sa.Column('location', sa.Text(), nullable=True),
        sa.Column('photos', sa.Text(), nullable=True),
        sa.Column('funding_goal', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['plUser_id'], ['plUser.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_title'),
                    'project', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
