"""empty message

Revision ID: 8560808e8ef9
Revises: 138c3900b932
Create Date: 2020-05-25 20:01:10.050480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8560808e8ef9'
down_revision = '138c3900b932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_pics', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expertise', sa.String(length=64), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=64), nullable=True),
    sa.Column('angelco_profile', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['plUser.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
