"""Create Industry table with a N-to-M relationship with Project. project_industries_map created 

Revision ID: a0c20a78eb62
Revises: 61ff6848a9c2
Create Date: 2020-05-22 22:05:36.680556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c20a78eb62'
down_revision = '61ff6848a9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('project_industries_map',
                    sa.Column('industry_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['industry_id'], ['industry.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.PrimaryKeyConstraint('industry_id', 'project_id')
                    )
    # industry is JOIN with project, not column explicity
    op.drop_column('project', 'industry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('industry', sa.TEXT(),
                                       autoincrement=False, nullable=True))
    op.drop_table('project_industries_map')
    op.drop_table('industry')
    # ### end Alembic commands ###
