"""empty message

Revision ID: d074b7e2159b
Revises: bb15a5c8eb7a
Create Date: 2020-05-26 13:58:15.232998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd074b7e2159b'
down_revision = 'bb15a5c8eb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('login_email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plUser_login_email'), 'plUser', ['login_email'], unique=True)
    op.create_index(op.f('ix_plUser_username'), 'plUser', ['username'], unique=True)
    op.create_table('profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_pics', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expertise', sa.String(length=64), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=64), nullable=True),
    sa.Column('angelco_profile', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['plUser.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_index(op.f('ix_plUser_username'), table_name='plUser')
    op.drop_index(op.f('ix_plUser_login_email'), table_name='plUser')
    op.drop_table('plUser')
    # ### end Alembic commands ###
