"""empty message

Revision ID: f655f745f5f3
Revises: bb15a5c8eb7a
Create Date: 2020-05-23 16:33:19.132889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f655f745f5f3'
down_revision = 'bb15a5c8eb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('login_email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plUser_login_email'), 'plUser', ['login_email'], unique=True)
    op.create_index(op.f('ix_plUser_username'), 'plUser', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plUser_username'), table_name='plUser')
    op.drop_index(op.f('ix_plUser_login_email'), table_name='plUser')
    op.drop_table('plUser')
    # ### end Alembic commands ###
